---
- name: Linux Security Hardening
  hosts: all
  become: yes
  gather_facts: yes

  collections:
    - community.general

  roles:
    - role: ssh-hardening
    - role: firewall-ufw  
    - role: auditd-hardening
    - role: cis-hardening
    - role: compliance
